repos:
  - repo: local
    hooks:
      - id: npm-lint
        name: npm run lint
        entry: npm run lint
        language: system
        pass_filenames: false
      - id: npm-typecheck
        name: npm run typecheck
        entry: npm run typecheck
        language: system
        pass_filenames: false
      - id: npm-test
        name: npm run test
        entry: npm run test
        language: system
        pass_filenames: false
