name: Go Worker Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go-worker/go.mod
      - name: Run Go worker tests
        run: go test ./...
        working-directory: go-worker
